from __future__ import annotations

from pathlib import Path

from .image_routes import DEFAULT_PPT_IMAGE_SIZE_16_9


IMAGE_API_PROVIDER = "openai_image_api"

DEFAULT_IMAGE_API_BASE_URL = "http://direct-api.cangyuansuanli.cn/"
DEFAULT_IMAGE_API_GENERATION_ENDPOINT = "/v1/images/generations"
DEFAULT_IMAGE_API_EDITS_ENDPOINT = "/v1/images/edits"
LEGACY_GRSAI_DRAW_COMPLETIONS_ENDPOINT = "/v1/draw/completions"

DEFAULT_IMAGE_API_MODEL = "gpt-image-2.5"
DEFAULT_IMAGE_API_SIZE = DEFAULT_PPT_IMAGE_SIZE_16_9
DEFAULT_IMAGE_API_QUALITY = "high"
DEFAULT_IMAGE_API_OUTPUT_FORMAT = "png"
DEFAULT_IMAGE_API_RESPONSE_FORMAT = "b64_json"
DEFAULT_IMAGE_API_PARALLELISM = 6
DEFAULT_IMAGE_API_TIMEOUT_SECONDS = 500

DEFAULT_IMAGE_API_KEY_ENV = "PPT_IMAGE_API_KEY"
DEFAULT_IMAGE_API_KEY_FILE_ENV = "PPT_IMAGE_API_KEY_FILE"
DEFAULT_IMAGE_API_BASE_URL_ENV = "PPT_IMAGE_API_BASE_URL"
DEFAULT_IMAGE_API_MODEL_ENV = "PPT_IMAGE_API_MODEL"
DEFAULT_IMAGE_API_SIZE_ENV = "PPT_IMAGE_API_SIZE"
DEFAULT_IMAGE_API_QUALITY_ENV = "PPT_IMAGE_API_QUALITY"
DEFAULT_IMAGE_API_RESPONSE_FORMAT_ENV = "PPT_IMAGE_API_RESPONSE_FORMAT"
DEFAULT_IMAGE_API_KEY_FILE = Path.home() / ".codex" / "secrets" / "ppt-skill-v3" / "image_api_key"

SUPPORTED_IMAGE_API_ENDPOINTS = {
    DEFAULT_IMAGE_API_GENERATION_ENDPOINT,
    DEFAULT_IMAGE_API_EDITS_ENDPOINT,
    LEGACY_GRSAI_DRAW_COMPLETIONS_ENDPOINT,
}
